import Head from 'next/head'
import Link from 'next/link'
import { Chewy } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'
import FirstSection from '../components/home'
import Second_section from '../components/second_section'

const chewy = Chewy({ weight:"400", subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Fuzzle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
      <div>
        <div className={styles.nav_area}>
          <div className={styles.app_title}>
          <h1 className={chewy.className}>Fuzzle</h1>
          </div>
          <nav className={styles.home_nav}>
            <Link href="/">Home</Link>
            <a href="/about">About Us</a>
            <a href="/quiz">Quiz</a>
            <a href="/adopt">Adopt</a>
            <a href="resource">Resource</a>
            <a href="/contact">Contact Us</a>
          </nav>
          <Image src="/Paw.png" width="0" height="0" style={{ width: '50px', height: 'auto' }} alt="paw print of a dog"/>
        </div>
      <FirstSection />
      <Second_section />
        <div>
          <h2>THIS IS WHERE FOOTER WILL GO</h2>
        </div>
      </div>
      </main>
    </>
  )
}
